### ISSUE TITLE
Pointer  customization

### ISSUE THREAD

**Issue by pliablepixels** [darul75/angular-awesome-slider#126]
Hello, I am facing a problem with using this slider in mobile devices - often the touch does not register when the pointer is too far left. I suspect this may be because the touch area of the pointer is too small.

So I am trying to increase the size of the pointer. I am using a custom class in options which I have used to change the scale color. I am probably not writing the class properly for pointer. Can you let me know?

```
.mySliderClass div.jslider-pointer ins
{
    width:40px;
    height:40px;
   
}
```

**Comment by darul75** [comment]
just change it to 

```css
.mySliderClass div.jslider-pointer {
    width:40px;
    height:40px;

}
```

**Comment by pliablepixels** [comment]
@darul75, I tried this version as well - it does not change the size. I just tried it again. Can you check?

For now I found the code in your library and modified it directly  (Not desirable) like this:
```
.jslider.sliderCSS.vertical div.jslider-pointer{left:50%;width:40px;height:40px;background-color:#615959;border-radius:50%;margin-left:-3px}
```

But when I tried to not modify your css and added it to myClass it did not work
```
.mySliderClass.jslider.sliderCSS.vertical div.jslider-pointer{left:50%;width:40px;height:40px;background-color:#615959;border-radius:50%;margin-left:-3px}
```
(I also modified the position of .mySliderClass div.jslider-value to accommodate the larger pointer)

**Comment by darul75** [comment]
yes avoid modifying my styles, which are in 'less' folder. to see changes, you need to start > grunt command then to generate all .css

```css
.mySliderClass.jslider.sliderCSS.vertical div.jslider-pointer{left:50%;width:40px;height:40px;background-color:#615959;border-radius:50%;margin-left:-3px}
```

if it is horizontal slider, remove 'vertical' selector

```css
.mySliderClass.jslider.sliderCSS div.jslider-pointer{left:50%;width:40px;height:40px;background-color:#615959;border-radius:50%;margin-left:-3px}
```
